### ISSUE TITLE
[Bug] Not all composers are listed

### ISSUE THREAD

**Issue by mslourens** [openopus-org/concertmaster_player#2]
I was looking for Antonio Lotti, which is present on Spotify, but Concertmaster could not find him. Is the list with composers hardcoded or generated by scraping the Spotify catalog.
If it's hardcoded, could you add Antonio Lotti to the list?

**Comment by adrianosbr** [comment]
The composer database doesn't come from Spotify, but from another project of mine, the Open Opus database (https://github.com/openopus-org/openopus_api). It's now restricted to a starter pack of 220 composers. In a few weeks the Open Opus database will become collaborative, accepting edits and new entries of composers/works from anyone on the web.
