### ISSUE TITLE
[Question] Should you be able to have multiple sessions playing different songs at the same time?

### ISSUE THREAD

**Issue by mslourens** [openopus-org/concertmaster_player#20]
It is possible to run a session in a browser and one in an installed PWA, or a session in two different browsers and play a different song at the same time. Should this be possible? Is the limitation on the Spotify side or on Concertmaster?
Note: sometimes one session is paused when you start playing in the other session, but this doesn't happen all the time. You have to play around with the different browsers, starting songs in different sessions. In the end I always get it working.

**Comment by adrianosbr** [comment]
It is perfectly possible to run many instances of Concertmaster you want, but your Spotify subscription will determine how many simultaneous streams you can start. Regular plans allow for only one device playing music; family plans allow for 5 simultaneous devices.

That's a limitation on the Spotify side. You can test it by yourself - play a track on Concertmaster and open your Spotify client. The Concertmaster track will show up on the Spotify client, and you can "transfer" it from Concertmaster to Spotify in a click.

**Comment by mslourens** [comment]
5 simultaneous devices doesn't mean 5 simultaneous sessions, because I have a family account but I login with the same account in multiple sessions at once. Sometimes Spotify allows me to do that, sometimes it stops playing one session and starts the other.
