### ISSUE TITLE
https://concertmaster.app certificate expired?

### ISSUE THREAD

**Issue by RalfNorthman** [openopus-org/concertmaster_player#33]
When i tried to go to the site concertmaster.app I was met with this in Firefox (win10):

![concertmaster](https://user-images.githubusercontent.com/26719710/136702490-b2740505-0c11-4133-b45c-b9237b38f701.png)

I checked my OS clock and it was accurate.

In Chrome it looks like this:

![concertmaster-chrome](https://user-images.githubusercontent.com/26719710/136702735-8d38a751-791c-4a87-9033-2b49ec53c72d.png)

I hope the last sentence in the Chrome message is correct and that this is a fleeting problem.

Interesting project that I'm keen to try out!

**Comment by adrianosbr** [comment]
Hi Ralf,

It was an issue with our SSL certificate. (.app domains require a valid
SSL.) It's working now!

Thank you!

**Comment by RalfNorthman** [comment]
Great! Thanks!
