### ISSUE TITLE
Refactor app

### ISSUE THREAD

**Issue by mslourens** [openopus-org/concertmaster_player#9]
I am thinking about splitting your code (index.html and lib.js) up into reusable components and bundle the external dependencies. This way the bundler (either webpack or roll-up) can get rid of unused pieces of code. 
The framework I am thinking of using is [Svelte](https://svelte.dev) , which is actually a compiler, and really fast. But if you have other ideas, let me know (like Vue, Angular or React). If you don't like it I will maybe try it as an exercise, to get some experience with Svelte.

**Comment by adrianosbr** [comment]
I'm no big fan of frameworks and I tried to avoid them all (jQuery apart, which I regret now). But feel free to refactor the code as you want, try it in your fork and we discuss it again at merge time :)

**Comment by mslourens** [comment]
I close this issue because I am unable to create a working development environment.
